# Generated by Django 4.1.1 on 2022-09-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cobro', models.CharField(choices=[('ex', 'EXTRA'), ('me', 'MENSUAL')], default='EXTRA', max_length=45)),
            ],
        ),
    ]
