# Generated by Django 4.1.1 on 2022-09-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servicio',
            new_name='servicios',
        ),
    ]
