# Generated by Django 4.1.1 on 2022-09-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_servicio_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='cod_servicio',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(default='SIN DESCRIPCION', max_length=255),
        ),
        migrations.AddField(
            model_name='servicios',
            name='multa_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicios',
            name='obs',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='servicios',
            name='tarifa',
            field=models.CharField(default='SIN TARIFA', max_length=255),
        ),
    ]
