# Generated by Django 4.1.1 on 2022-09-26 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicios_cod_servicio_servicios_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'managed': False},
        ),
    ]
