# Generated by Django 4.1.1 on 2022-09-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_servicios_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicios',
            table='servicios',
        ),
    ]
