# Generated by Django 4.1.1 on 2022-10-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_tarifa_delete_tarifas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('cod_socio', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('codigo_anterior', models.CharField(max_length=45)),
                ('ci', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_factura_luz', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidad_ingreso', models.CharField(max_length=55)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(max_length=45)),
                ('zona', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('manzano', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=255)),
                ('frente_ml', models.FloatField()),
                ('superficie', models.FloatField()),
                ('rta', models.CharField(max_length=45)),
                ('fecha_rta', models.DateField()),
                ('codigo_catastral', models.CharField(max_length=55)),
                ('obs', models.CharField(max_length=255)),
                ('orden_manzano', models.IntegerField()),
                ('categoria', models.CharField(max_length=45)),
                ('generar_cobros', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'socios',
                'managed': False,
            },
        ),
    ]
