# Generated by Django 4.1.1 on 2022-10-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SociosServicio',
            fields=[
                ('cod_socio', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('cod_servicio', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'socios_servicios',
                'managed': False,
            },
        ),
    ]
